name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
  tf_vars:
    description: "Terraform customer config"
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
  tf_ansible:
    description: "Terraforn Ansible config"
    value: tf_ansible.yaml
runs:
  using: "composite"
  steps:
    - uses: hashicorp/setup-terraform@v2
    - run: |
        echo "Current path: $(pwd)"
      shell: bash
    - run: |
        pwd
        terraform -chdir=$GITHUB_WORKSPACE/infra init
      shell: bash
    - run: |
        echo "Terraform vars"
        cat ${{ inputs.tf_vars }}
      shell: bash
    - run: |
        echo "---\ntf_hostname: blablavla" > tf_ansible.yaml
      shell: bash
