name: 'TDV Provision'
description: 'Provision TDV server'
inputs:
  tf_vars:
    description: "Terraform customer config"
    required: true
outputs:
  tf_ansible:
    description: "Terraforn Ansible config"
    value: tf_ansible.yaml
runs:
  using: "composite"
  steps:
    - uses: hashicorp/setup-terraform@v2
    - run: |
        terraform -chdir=$GITHUB_WORKSPACE/infra init
      shell: bash
    - run: |
        echo "Terraform vars"
        cat ${{ inputs.tf_vars }}
      shell: bash
    - run: |
        echo "---\ntf_hostname: blablavla" > tf_ansible.yaml
      shell: bash
